---
# yaml document template for data management configuration

DATA_FILETYPE: 'parquet'

ENGINE: 'polars_lazy'

PROVIDERS_KEY: 
    ALPHA_VANTAGE_KEY : <ALPHA-VANTAGE-API-KEY>, 
    POLYGON_IO_KEY    : <POLYGON-IO-API-KEY>
    