---
# yaml document template for data management configuration

DATA_FILETYPE: 'parquet'
ENGINE: 'polars_lazy'
DATA_PATH: 'ABSOLUTE-PATH-TO-DATA-DIRECTORY'

PROVIDERS_KEY: 
    ALPHA_VANTAGE_KEY : <ALPHA-VANTAGE-API-KEY>, 
    POLYGON_IO_KEY    : <POLYGON-IO-API-KEY>


    